### ISSUE TITLE
contributing vivado to nixpkgs repo

### ISSUE THREAD

**Issue by matthuszagh** [lukaslaobeyer/nix-fpgapkgs#1]
I use your vivado build expression and was hoping to submit it to the [nixpkgs repo](https://github.com/NixOS/nixpkgs) for others to benefit from. Do you mind if I create a PR there? I've made a few minor edits, but most of the work is yours.

**Comment by lukaslaobeyer** [comment]
Yes, feel free to do so. It would be great to have Vivado included in nixpkgs. Thanks!

**Comment by matthuszagh** [comment]
Thanks!
