### ISSUE TITLE
Free software license

### ISSUE THREAD

**Issue by lschuermann** [lukaslaobeyer/nix-fpgapkgs#2]
Thank you very much for you work in getting Xilinx Vivado to build with Nix.

I'd like to use the Nix derivations as part of a larger Nix evaluation for generating bitstreams automatically. I've updated the derivations to work with a more recent version of Xilinx Vivado accordingly. To be able to license & publish my work under a free software license I'd kindly ask you to assign a license to you work.

I would recommend the MIT license here, such that it will be compatible with nixpkgs for upstreaming the work.

Since you have given permission to upstream your work to @matthuszagh in #1, this appears to have been an explicit permission to relicense your work under the MIT license (as required by nixpkgs), but adding an explicit license file is probably better. :smile: 

Thanks!

**Comment by lukaslaobeyer** [comment]
I'm glad to hear you found this useful. Looking forward to seeing and using your updated version!

I agree the MIT license makes sense here and added the appropriate license file.

Thank you!

**Comment by lschuermann** [comment]
Thanks! In case you're interested, I've released the modified version [here](https://github.com/lschuermann/tock-litex/blob/master/pkgs/vivado/default.nix). It's probably not the most beautiful derivation and does allocate some more space in the Nix store (as the unpacked derivation is stored too), but seems to work with Vivado 2020.1. A garbage collect after building removes the intermediate unpacked derivation. Feel free to pull the changes back in.
